package com.qiplat.compose.sweeteditor.theme

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.toArgb

internal data class SweetEditorColorsInternal(
    val background: Int,
    val text: Int,
    val cursor: Int,
    val selection: Int,
    val lineNumber: Int,
    val currentLineNumber: Int,
    val currentLine: Int,
    val guide: Int,
    val separatorLine: Int,
    val splitLine: Int,
    val scrollbarTrack: Int,
    val scrollbarThumb: Int,
    val scrollbarThumbActive: Int,
    val compositionUnderline: Int,
    val inlayHintBackground: Int,
    val inlayHintText: Int,
    val foldPlaceholderBackground: Int,
    val foldPlaceholderText: Int,
    val phantomText: Int,
    val inlayHintIcon: Int,
    val diagnosticError: Int,
    val diagnosticWarning: Int,
    val diagnosticInfo: Int,
    val diagnosticHint: Int,
    val linkedEditingActive: Int,
    val linkedEditingInactive: Int,
    val bracketHighlightBorder: Int,
    val bracketHighlightBackground: Int,
    val gutterBackground: Int,
)

data class SweetEditorColors(
    val background: Color,
    val text: Color,
    val cursor: Color,
    val selection: Color,
    val lineNumber: Color,
    val currentLineNumber: Color,
    val currentLine: Color,
    val guide: Color,
    val separatorLine: Color,
    val splitLine: Color,
    val scrollbarTrack: Color,
    val scrollbarThumb: Color,
    val scrollbarThumbActive: Color,
    val compositionUnderline: Color,
    val inlayHintBackground: Color,
    val inlayHintText: Color,
    val foldPlaceholderBackground: Color,
    val foldPlaceholderText: Color,
    val phantomText: Color,
    val inlayHintIcon: Color,
    val diagnosticError: Color,
    val diagnosticWarning: Color,
    val diagnosticInfo: Color,
    val diagnosticHint: Color,
    val linkedEditingActive: Color,
    val linkedEditingInactive: Color,
    val bracketHighlightBorder: Color,
    val bracketHighlightBackground: Color,
    val gutterBackground: Color,
) {
    private val internalColors: SweetEditorColorsInternal = SweetEditorColorsInternal(
        background = background.toArgb(),
        text = text.toArgb(),
        cursor = cursor.toArgb(),
        selection = selection.toArgb(),
        lineNumber = lineNumber.toArgb(),
        currentLineNumber = currentLineNumber.toArgb(),
        currentLine = currentLine.toArgb(),
        guide = guide.toArgb(),
        separatorLine = separatorLine.toArgb(),
        splitLine = splitLine.toArgb(),
        scrollbarTrack = scrollbarTrack.toArgb(),
        scrollbarThumb = scrollbarThumb.toArgb(),
        scrollbarThumbActive = scrollbarThumbActive.toArgb(),
        compositionUnderline = compositionUnderline.toArgb(),
        inlayHintBackground = inlayHintBackground.toArgb(),
        inlayHintText = inlayHintText.toArgb(),
        foldPlaceholderBackground = foldPlaceholderBackground.toArgb(),
        foldPlaceholderText = foldPlaceholderText.toArgb(),
        phantomText = phantomText.toArgb(),
        inlayHintIcon = inlayHintIcon.toArgb(),
        diagnosticError = diagnosticError.toArgb(),
        diagnosticWarning = diagnosticWarning.toArgb(),
        diagnosticInfo = diagnosticInfo.toArgb(),
        diagnosticHint = diagnosticHint.toArgb(),
        linkedEditingActive = linkedEditingActive.toArgb(),
        linkedEditingInactive = linkedEditingInactive.toArgb(),
        bracketHighlightBorder = bracketHighlightBorder.toArgb(),
        bracketHighlightBackground = bracketHighlightBackground.toArgb(),
        gutterBackground = gutterBackground.toArgb(),
    )

    internal fun toInternal(): SweetEditorColorsInternal = internalColors

    internal companion object {
        fun fromInternal(colors: SweetEditorColorsInternal): SweetEditorColors = SweetEditorColors(
            background = Color(colors.background),
            text = Color(colors.text),
            cursor = Color(colors.cursor),
            selection = Color(colors.selection),
            lineNumber = Color(colors.lineNumber),
            currentLineNumber = Color(colors.currentLineNumber),
            currentLine = Color(colors.currentLine),
            guide = Color(colors.guide),
            separatorLine = Color(colors.separatorLine),
            splitLine = Color(colors.splitLine),
            scrollbarTrack = Color(colors.scrollbarTrack),
            scrollbarThumb = Color(colors.scrollbarThumb),
            scrollbarThumbActive = Color(colors.scrollbarThumbActive),
            compositionUnderline = Color(colors.compositionUnderline),
            inlayHintBackground = Color(colors.inlayHintBackground),
            inlayHintText = Color(colors.inlayHintText),
            foldPlaceholderBackground = Color(colors.foldPlaceholderBackground),
            foldPlaceholderText = Color(colors.foldPlaceholderText),
            phantomText = Color(colors.phantomText),
            inlayHintIcon = Color(colors.inlayHintIcon),
            diagnosticError = Color(colors.diagnosticError),
            diagnosticWarning = Color(colors.diagnosticWarning),
            diagnosticInfo = Color(colors.diagnosticInfo),
            diagnosticHint = Color(colors.diagnosticHint),
            linkedEditingActive = Color(colors.linkedEditingActive),
            linkedEditingInactive = Color(colors.linkedEditingInactive),
            bracketHighlightBorder = Color(colors.bracketHighlightBorder),
            bracketHighlightBackground = Color(colors.bracketHighlightBackground),
            gutterBackground = Color(colors.gutterBackground),
        )
    }
}

