title: SweetEditor Docs
description: A Multifunctional code editor library for compose multiplatform（It is not the BasicTextField enhancement）
theme: jekyll-theme-cayman
markdown: kramdown
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
